name=M5Unit-HUB
version=0.3.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT HUB using M5UnitUnified
paragraph=Supports PaHub (PCA9548AP, I2C mux) and PbHub (STM32F030, Port.B expander).
category=Device Control
url=https://github.com/m5stack/M5Unit-HUB
architectures=esp32
includes=M5UnitUnifiedHUB.h
depends=M5UnitUnified,M5Utility,M5HAL
